name: mysql-strict
version: '9.2.0'
summary: Powerful open-source relational database management system
description: |
  Developed by Oracle®, MySQL is the world's most popular open-source relational
  database management system. The MySQL website (http://www.mysql.com/) provides
  the latest information about MySQL software.

base: core24
grade: stable
confinement: strict
license: GPL-3.0

slots:
  mysql-socket:
    interface: content
    content: socket-directory
    write:
      - $SNAP_DATA/run

hooks:
  install:
    plugs: [network, network-bind]
    command-chain:
      - snap/command-chain/install.sh

system-usernames:
  snap_daemon: shared

apps:
  mysqld:
    command: bin/mysqld.sh
    daemon: simple
    plugs: [network, network-bind]
  mysql:
    command: usr/bin/mysql
    plugs: [network, home, removable-media]
  mysqladmin:
    command: usr/bin/mysqladmin
    plugs: [network, home, removable-media]
  mysqldump:
    command: usr/bin/mysqldump
    plugs: [network, home, removable-media]
  mysqlimport:
    command: usr/bin/mysqlimport
    plugs: [network, home, removable-media]
  mysql-secure-installation:
    command: usr/bin/mysql_secure_installation

parts:
  local:
    plugin: dump
    source-type: local
    source: snap/local
    override-stage: |
      craftctl default
      sed -i 's/_NAME_/$SNAPCRAFT_PROJECT_NAME/g' bin/*.sh
      sed -i 's/_NAME_/$SNAPCRAFT_PROJECT_NAME/g' etc/*.cnf
  mysql:
    after: [local]
    plugin: cmake
    source: https://cdn.mysql.com/Downloads/MySQL-9.2/mysql-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_CONFIG=mysql_release
      - -DCMAKE_BUILD_TYPE=Release
      - -DWITH_UNIT_TESTS=OFF
      - -DWITH_DEBUG=OFF
      - -DINSTALL_MYSQLTESTDIR=
      - -DWITH_SYSTEMD=OFF
      - -DMYSQL_DATADIR=/var/snap/$SNAPCRAFT_PROJECT_NAME/common/data
      - -DMYSQL_UNIX_ADDR=/var/snap/$SNAPCRAFT_PROJECT_NAME/current/run/mysql.sock
      - -DMYSQLX_UNIX_ADDR=/var/snap/$SNAPCRAFT_PROJECT_NAME/current/run/mysqlx.sock
    build-packages:
      - build-essential
      - pkg-config
      - libssl-dev
      - libncurses5-dev
      - libaio-dev
      - libtirpc-dev
      - bison
      - util-linux
    override-build: |
      patch $CRAFT_PART_SRC/client/mysql_secure_installation.cc $CRAFT_STAGE/build/mysql_secure_installation-remove-root-pw-creation.patch
      craftctl default
    stage-packages:
      - libaio1t64
    override-prime: |
      craftctl default
      if [ ! -d bin ] ; then mkdir bin ; fi
      cp /usr/bin/setpriv bin/
      find "usr/bin" -type f -exec sh -c 'grep -IL . "$1" || strip --strip-all "$1"' sh "{}" \;
      rm -r build/
