name: mysql-strict
version: '8.0.36'
summary: Powerful open-source relational database management system
description: |
  Developed by Oracle®, MySQL is the world's most popular open-source relational
  database management system. The MySQL website (http://www.mysql.com/) provides
  the latest information about MySQL software.

base: core22
grade: stable
confinement: strict
license: GPL-3.0

slots:
  mysql-socket:
    interface: content
    content: socket-directory
    write:
      - $SNAP_DATA/run

hooks:
  install:
    command-chain:
      - snap/command-chain/install.sh
  #post-refresh:
  #  command-chain:
  #    - snap/command-chain/refresh_run.sh

system-usernames:
  snap_daemon: shared

apps:
  mysqld:
    command: bin/mysqld.sh
    daemon: simple
    plugs: [network, network-bind]
  mysql:
    command: usr/bin/mysql
  mysqladmin:
    command: usr/bin/mysqladmin
  mysqldump:
    command: usr/bin/mysqldump
  mysqlimport:
    command: usr/bin/mysqlimport
  rootpass:
    command: bin/rootpass.sh

parts:
  mysql:
    plugin: cmake
    source: https://cdn.mysql.com/Downloads/MySQL-8.0/mysql-boost-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_CONFIG=mysql_release
      - -DCMAKE_BUILD_TYPE=Release
      - -DWITH_UNIT_TESTS=OFF
      - -DWITH_DEBUG=OFF
      - -DWITH_INNODB_EXTRA_DEBUG=OFF
      - -DINSTALL_MYSQLTESTDIR=
      - -DDOWNLOAD_BOOST=OFF
      - -DWITH_BOOST=$CRAFT_PART_SRC/boost
      - -DWITH_SYSTEMD=OFF
      - -DMYSQL_DATADIR=/var/snap/$SNAPCRAFT_PROJECT_NAME/common/data
      - -DMYSQL_UNIX_ADDR=/var/snap/$SNAPCRAFT_PROJECT_NAME/current/run/mysql.sock
      - -DMYSQLX_UNIX_ADDR=/var/snap/$SNAPCRAFT_PROJECT_NAME/current/run/mysqlx.sock
    build-packages:
      - build-essential
      - pkg-config
      - libssl-dev
      - libncurses5-dev
      - util-linux
    override-prime: |
      craftctl default
      if [ ! -d bin ] ; then mkdir bin ; fi
      cp /usr/bin/setpriv bin/
      find "usr/bin" -type f -exec sh -c 'grep -IL . "$1" || strip --strip-all "$1"' sh "{}" \;
  local:
    plugin: dump
    source-type: local
    source: snap/local
    override-prime: |
      craftctl default
      sed -i 's/_NAME_/$SNAPCRAFT_PROJECT_NAME/g' bin/*.sh
      sed -i 's/_NAME_/$SNAPCRAFT_PROJECT_NAME/g' etc/*.cnf
